layout_spectrum: 0.4892473
typography_spectrum: 0.8028674
color:
  saturation: 0.4188123
  lightness: 0.9211469
  brandStrength: 0.1218638
  rhythmicContrast: 0.1111111
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Mino Bimaadiziwin
